### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by facultymatt** [Aenima4six2/gmg#10]
- probe 2 temp and desired temp (current GMG grills have 2 probes)
- profile info, current step, completed steps, etc.

Awesome work on this - I was thrilled to see this existed! Cooking a brisket now and looking at the data from my new GMG grill!

**Comment by facultymatt** [comment]
Update - I was able to read food probe 2 current and desired temps using this code

```
const test = (hex, start) => {
  const first = getRawValue(hex, start)
  const second = getRawValue(hex, start + 2)
  return first + (second * 256)
}

this.test_32 = test(hex, 32); // _C2T = Current Food probe 2 temp
this.test_36 = test(hex, 36); // _D2T = Desired Food probe 2 temp
```

**Comment by facultymatt** [comment]
I have no idea about profile data, though... I suspect you need to relate them to codes in the app itself to interpret.

**Comment by Aenima4six2** [comment]
@facultymatt submit a PR for probe two and we will get it merged.
