### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by bwhitson** [Aenima4six2/gmg#12]
Great project.... Just got it up and running and the Slack tie in is great!!!!! Any chance you could point me in the direction of the REST documentation? Or if you can point to where in the code you used the REST API I work up a doc. I did find a few in src/gmg-app/src/utills but it looks like those are just set points that can be changed. I'd like to be able to query the device from the API if possible. Working on a bridge between your app and Home Assistant. 

Thanks,
B

**Comment by Aenima4six2** [comment]
Thanks so much. Unfortunately, I never added swagger docs or rest specs. All of the api routes are located at https://github.com/Aenima4six2/gmg/blob/master/src/gmg-server/routes/api.js. Let me know if you need any help getting setup.

**Comment by fgonza2** [comment]
> Great project.... Just got it up and running and the Slack tie in is great!!!!! Any chance you could point me in the direction of the REST documentation? Or if you can point to where in the code you used the REST API I work up a doc. I did find a few in src/gmg-app/src/utills but it looks like those are just set points that can be changed. I'd like to be able to query the device from the API if possible. Working on a bridge between your app and Home Assistant.
> 
> Thanks,
> B

Hi were you able to make it work with home assistant? i am trying to do the same

**Comment by fgonza2** [comment]
> Thanks so much. Unfortunately, I never added swagger docs or rest specs. All of the api routes are located at https://github.com/Aenima4six2/gmg/blob/master/src/gmg-server/routes/api.js. Let me know if you need any help getting setup.

Hi i am trying to use rest too, when i send a GET using POSTMAN as a client.   i get "Not found"   i am using the following URL

192.168.7.235:8080/status

I changed the port to 8080 and i can see the web browser working,  how can i perform a GET REST query for status?

thanks

**Comment by Biohazord** [comment]
@fgonza2 Which portions of the stack are you running? From what I can tell it looks like you're trying to query the status from the grill itself or the emulator. In this case the API is actually coming from `gmg-server`.

For me I start up `gmg-emulator` with `dotnet ./bin/Debug/netcoreapp2.1/gmg-emulator.dll` then `gmg-server` with `npm run start:dev` .  After that I can query the API VIA 
```
curl --request GET \
  --url http://localhost:3001/api/status
```

All the routes defined in `src/gmg-server/routes/api` should be accessible with that IP
