### ISSUE TITLE
Docker error 404

### ISSUE THREAD

**Issue by photinus** [Aenima4six2/gmg#4]
Deployed Docker image per instructions, Getting a 404 error when trying to load the web interface.

Here is the logs:

` gmg-server@0.0.0 start:release /app/gmg-server

> export NODE_ENV=production && export DEBUG=src.* && export PORT=80 && node ./bin/www

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.

WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

  src:gmg-client Attempting grill discovery... +0ms

  src:gmg-client Grill (172.20.0.100:8080) discovery broadcast dgram sent -> Attempt #1 +2s

  src:gmg-client Received discovery response dgram from Grill (172.20.0.100:8080) +84ms

  src:SocketManager Starting Socket Manager... +0ms

  src:SocketManager Socket Manager started! +1ms

  src:AlertManager Starting Alert Manager... +0ms

  src:PollingClient Polling Manager polling +0ms

  src:www Listening on port 80 +0ms

  src:PollingClient Polling Manager invoking task -> Attempt #1 +5s

  src:PollingClient Fetching grill status +1ms

  src:gmg-client Grill (172.20.0.100:8080) [UR001!] command dgram sent -> Attempt #1. +7s

  src:gmg-client Received response dgram from Grill (172.20.0.100:8080) +35ms

  src:SocketManager Waiting for connections... +7s

  src:AlertManager Executing alert handlers: [lowPelletAlarmActive.js, targetFoodTempReached.js, targetGrillTempReached.js] +7s

  src:AlertManager Sending alert for: [targetGrillTempReached] with senders: [SocketSender.js, SlackSender.js] +3ms

  src:SocketManager Waiting for connections... +5ms

GET / 404 10.006 ms - 9

GET /favicon.ico 404 3.090 ms - 9
`

**Comment by Aenima4six2** [comment]
@photinus Was able to repro the issue. Looks like one of the copy directives in the docker multi stage build got removed. Should be fixed now.

**Comment by photinus** [comment]
That fixed it! Thanks! Looking forward to playing with this.
