### ISSUE TITLE
Unsure how to get app to pull in browser (Suggest Readme update)

### ISSUE THREAD

**Issue by mrshake** [Aenima4six2/gmg#7]
I've cloned the app, I've got the server running and connected to my grill.  But I can't seem to figure out how to connect.  If I try just localhost, I get an error.  Its not clear in the readme

**Comment by Aenima4six2** [comment]
Are you running in a container or locally?

**Comment by mrshake** [comment]
Locally, on a mac

**Comment by Aenima4six2** [comment]
Fix on the way.

**Comment by Aenima4six2** [comment]
Fixed. Please re-open if you still have issues.
