### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ajgisler** [Aenima4six2/gmg#8]
Hello, 

Could you confirm this still works? I have tried getting this working on linux with virtualbox but haven't been successfully.
I then came across a website that had done security analysis on the GMG. Of course being an IoT device, they found the security was really week. According to the article GMG acknowledged the findings. This was May of this year, so I am wondering if they have fixed the security problems. Sniffing my network it does appear the data is being encrypted now. 

I am really interested in building my own app to control the grill. 

Thanks,
Andrew

**Comment by baron42bba** [comment]
Hi Andrew!
I had it running a few weeks ago under OSX 10.14 with macports.
Grill is current firmware.

**Comment by Aenima4six2** [comment]
Confirmed working :)
