### ISSUE TITLE
[Informational] Thanks for your reverse engineering efforts!

### ISSUE THREAD

**Issue by codahq** [Aenima4six2/gmg#9]
@Aenima4six2 Hi, thank you for figuring out the communication to the grill.  I was able to use the information here to create an integration into Hubitat.

https://community.hubitat.com/t/release-green-mountain-grill/34720

I'm posting it here in case somebody finds it interesting or useful for other similar activities or integrations.

**Comment by Aenima4six2** [comment]
Glad you found the project useful!
